#!/usr/bin/env python3
"""coverage_report.py — auto-generate tests/COVERAGE.md.

Walks every `Week N/java/` directory, enumerates the numbered topic files
(e.g. `1.ReturnArraySum.java`), and checks whether a matching
`tests/cases/<topic>.json` fixture exists. The topic identifier is the Java
class name stem converted to snake_case.

Legacy survey files (e.g. `fundamentals.java`, `arrays.java`) and any other
non-numbered files are intentionally skipped — those are pedagogical
overview modules, not individual algorithm topics.

Idempotent: running the script twice yields identical output.

Usage:
    python scripts/coverage_report.py

Writes `tests/COVERAGE.md`.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CASES_DIR = REPO_ROOT / "tests" / "cases"
OUTPUT_FILE = REPO_ROOT / "tests" / "COVERAGE.md"
TOTAL_WEEKS = 30

# Topic files start with a number followed by '.' or whitespace, e.g.
# "1.ReturnArraySum.java" or "14. How other datatype are stores.java".
NUMBERED_PREFIX = re.compile(r"^(\d+)[.\s]")


def snake_case(name: str) -> str:
    """Convert a Java-style file stem (CamelCase / mixed) to snake_case.

    Examples:
        ReturnArraySum         -> return_array_sum
        KMPSearch              -> kmp_search
        MergeSortedListsAndLRU -> merge_sorted_lists_and_lru
        Hello World            -> hello_world
        Add_two_numbers        -> add_two_numbers
    """
    # Replace whitespace and hyphens with underscores first, collapse runs.
    s = re.sub(r"[\s\-]+", "_", name.strip())
    # Insert underscore between an acronym run and a following CamelCase word
    # (e.g. "KMPSearch" -> "KMP_Search").
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", s)
    # Insert underscore between a lowercase/digit and an uppercase letter
    # (e.g. "ReturnArray" -> "Return_Array").
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    # Collapse repeated underscores, strip, lowercase.
    s = re.sub(r"_+", "_", s).strip("_").lower()
    return s


def topic_from_filename(filename: str) -> str | None:
    """Extract the topic identifier from a numbered Java filename.

    Returns None if the file is not a numbered topic file (e.g. a legacy
    survey module like `fundamentals.java`).
    """
    m = NUMBERED_PREFIX.match(filename)
    if not m:
        return None
    # Strip leading "<digits>[.\s]" and the trailing extension.
    rest = filename[m.end():]
    # Drop extension (.java) — handle the case where the prefix included a dot
    # already consumed.
    stem = rest.rsplit(".", 1)[0] if "." in rest else rest
    if not stem.strip():
        return None
    return snake_case(stem)


def enumerate_week_topics(week: int) -> list[tuple[str, str]]:
    """Return [(original_filename, normalized_topic)] for a week's java dir."""
    java_dir = REPO_ROOT / f"Week {week}" / "java"
    if not java_dir.is_dir():
        return []
    topics: list[tuple[str, str]] = []
    seen: set[str] = set()
    for entry in sorted(java_dir.iterdir(), key=lambda p: p.name):
        if not entry.is_file():
            continue
        if not entry.name.endswith(".java"):
            continue
        topic = topic_from_filename(entry.name)
        if topic is None:
            continue
        if topic in seen:
            continue
        seen.add(topic)
        topics.append((entry.name, topic))
    return topics


def fixture_exists(topic: str) -> bool:
    return (CASES_DIR / f"{topic}.json").is_file()


def build_report() -> str:
    per_week: dict[int, list[tuple[str, bool]]] = {}
    for n in range(1, TOTAL_WEEKS + 1):
        topics = enumerate_week_topics(n)
        per_week[n] = [(t, fixture_exists(t)) for _, t in topics]

    total_topics = sum(len(v) for v in per_week.values())
    total_tested = sum(1 for v in per_week.values() for _, ok in v if ok)
    overall_pct = (100.0 * total_tested / total_topics) if total_topics else 0.0

    lines: list[str] = []
    lines.append("# Test Coverage Report")
    lines.append("")
    lines.append(
        "Auto-generated by `scripts/coverage_report.py`. "
        "Run after adding new fixtures."
    )
    lines.append("")
    lines.append(
        f"**Overall: {total_tested}/{total_topics} topics tested "
        f"({overall_pct:.1f}%)**"
    )
    lines.append("")
    lines.append("## Per-week coverage")
    lines.append("")
    lines.append("| Week | Total Topics | Tested | Untested topics |")
    lines.append("|------|--------------|--------|-----------------|")
    for n in range(1, TOTAL_WEEKS + 1):
        topics = per_week[n]
        total = len(topics)
        if total == 0:
            lines.append(f"| {n} | 0 | 0/0 | (no numbered topic files) |")
            continue
        tested = sum(1 for _, ok in topics if ok)
        untested = [t for t, ok in topics if not ok]
        if not untested:
            untested_col = "all covered"
        else:
            untested_col = ", ".join(untested)
        lines.append(f"| {n} | {total} | {tested}/{total} | {untested_col} |")
    lines.append("")
    lines.append("## Priority gaps (Weeks 6+ where coverage <50%)")
    lines.append("")
    gaps: list[str] = []
    for n in range(6, TOTAL_WEEKS + 1):
        topics = per_week[n]
        total = len(topics)
        if total == 0:
            continue
        tested = sum(1 for _, ok in topics if ok)
        pct = tested / total
        if pct < 0.5:
            missing = [t for t, ok in topics if not ok]
            gaps.append(f"- Week {n}: {tested}/{total} ({', '.join(missing)})")
    if gaps:
        lines.extend(gaps)
    else:
        lines.append("- (none — every Week 6+ topic with files has >=50% coverage)")
    lines.append("")
    lines.append("## How to add a fixture")
    lines.append("")
    lines.append("1. Pick an untested topic from above.")
    lines.append("2. Create `tests/cases/<topic>.json` with 4-6 cases per SCHEMA.md.")
    lines.append("3. Create `tests/refs/<topic>.py` exposing the canonical function.")
    lines.append("4. Optional: add C++/Java/Rust drivers (see existing patterns).")
    lines.append("5. Run `python tests/harness/harness.py --all`. Re-run this script.")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    report = build_report()
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    # Idempotent write: only touch the file if contents changed.
    existing = OUTPUT_FILE.read_text() if OUTPUT_FILE.exists() else None
    if existing != report:
        OUTPUT_FILE.write_text(report)
        action = "wrote"
    else:
        action = "unchanged"
    # Echo a one-line summary so CI logs surface the coverage %.
    first_summary = next(
        (ln for ln in report.splitlines() if ln.startswith("**Overall:")),
        "Overall: unknown",
    )
    print(f"coverage_report: {action} {OUTPUT_FILE.relative_to(REPO_ROOT)} — "
          f"{first_summary.strip('*')}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
