#!/usr/bin/env python3
"""generate_showcase_index.py — rebuilds showcase/SUBMISSIONS.md.

Reads every `showcase/submissions/*.md` file, parses YAML frontmatter, and
emits a Markdown table indexed by date. Files without valid frontmatter are
skipped with a warning to stderr (the script still exits 0 unless --strict
is passed).

Stdlib + PyYAML.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write(
        "error: PyYAML is required. Install with: pip install pyyaml\n"
    )
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parent.parent
SUBMISSIONS_DIR = REPO_ROOT / "showcase" / "submissions"
INDEX_PATH = REPO_ROOT / "showcase" / "SUBMISSIONS.md"

FRONTMATTER_KEYS = (
    "name",
    "capstone",
    "repo_url",
    "github_handle",
)


def parse_frontmatter(text: str) -> dict | None:
    """Return the YAML frontmatter dict, or None if missing/invalid."""
    if not text.startswith("---"):
        return None
    lines = text.splitlines()
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return None
    block = "\n".join(lines[1:end])
    try:
        data = yaml.safe_load(block)
    except yaml.YAMLError:
        return None
    if not isinstance(data, dict):
        return None
    return data


def collect_submissions(strict: bool = False) -> list[dict]:
    items: list[dict] = []
    if not SUBMISSIONS_DIR.exists():
        return items
    for path in sorted(SUBMISSIONS_DIR.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)
        if fm is None:
            msg = f"warning: {path.name} has no/invalid frontmatter; skipping"
            sys.stderr.write(msg + "\n")
            if strict:
                sys.exit(1)
            continue
        missing = [k for k in FRONTMATTER_KEYS if not fm.get(k)]
        if missing:
            msg = (
                f"warning: {path.name} missing keys {missing}; skipping"
            )
            sys.stderr.write(msg + "\n")
            if strict:
                sys.exit(1)
            continue
        item = {
            "name": str(fm.get("name", "")).strip(),
            "capstone": str(fm.get("capstone", "")).strip(),
            "repo_url": str(fm.get("repo_url", "")).strip(),
            "github_handle": str(fm.get("github_handle", "")).strip(),
            "demo_url": str(fm.get("demo_url", "")).strip(),
            "date_finished": str(fm.get("date_finished", "")).strip(),
            "languages": fm.get("languages") or [],
            "file": path.name,
        }
        items.append(item)
    # Sort newest first by date_finished (empty dates last), then by name.
    items.sort(key=lambda it: (it["date_finished"] == "", it["date_finished"]), reverse=True)
    return items


def _md_escape(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


def render_index(items: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# Showcase — Submissions")
    lines.append("")
    lines.append(
        "Auto-generated by [`scripts/generate_showcase_index.py`](../scripts/generate_showcase_index.py). "
        "Do not edit by hand — edit the individual `showcase/submissions/*.md` files and re-run the script. "
        "See [`README.md`](README.md) for how to add yourself."
    )
    lines.append("")

    if not items:
        lines.append("_No submissions yet. Be the first — see [`README.md`](README.md)._")
        lines.append("")
        return "\n".join(lines)

    lines.append(f"Total submissions: **{len(items)}**")
    lines.append("")
    lines.append("| Date | Project | Capstone | Author | Languages | Links |")
    lines.append("|---|---|---|---|---|---|")
    for it in items:
        languages = ", ".join(it["languages"]) if isinstance(it["languages"], list) else str(it["languages"])
        handle = it["github_handle"]
        author_md = f"[@{handle}](https://github.com/{handle})" if handle else ""
        links: list[str] = []
        if it["repo_url"]:
            links.append(f"[repo]({it['repo_url']})")
        if it["demo_url"]:
            links.append(f"[demo]({it['demo_url']})")
        links.append(f"[writeup](submissions/{it['file']})")
        lines.append(
            "| {date} | {name} | {capstone} | {author} | {langs} | {links} |".format(
                date=_md_escape(it["date_finished"] or "—"),
                name=_md_escape(it["name"]),
                capstone=_md_escape(it["capstone"]),
                author=author_md,
                langs=_md_escape(languages or "—"),
                links=" / ".join(links),
            )
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Rebuild showcase/SUBMISSIONS.md")
    ap.add_argument("--strict", action="store_true", help="exit non-zero on any malformed submission")
    ap.add_argument("--check", action="store_true", help="don't write; exit 1 if current index differs from generated")
    args = ap.parse_args(argv)

    items = collect_submissions(strict=args.strict)
    rendered = render_index(items)

    if args.check:
        current = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""
        if current.strip() != rendered.strip():
            sys.stderr.write("showcase/SUBMISSIONS.md is out of date — run scripts/generate_showcase_index.py\n")
            return 1
        return 0

    INDEX_PATH.write_text(rendered, encoding="utf-8")
    sys.stdout.write(f"Wrote {INDEX_PATH.relative_to(REPO_ROOT)} ({len(items)} submissions).\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
